### ISSUE TITLE
mit数据库疑问

### ISSUE THREAD

**Issue by zuoguangxing11** [Asues/Matlab#3]
你好，我最近也在研究3d音效。请问是否有使用过mit database里的wav文件进行过实验呢？

**Comment by THBratwurst** [comment]
这个不好意思，我没有用过这个数据库里的音频文件。我是当年的本科毕业论文用到的学校提供的wav数据，主要有人声，器乐（萨克斯）和白噪音三种音频数据来测试，不过原理应该是大同小异的。

**Comment by zuoguangxing11** [comment]
还有几个问题请教:数据库使用wav文件的话。
1.wav文件里存的是不是空间位置点的hrir数据？理论来讲读取了wav文件的数据，获取到了hrir数据，与待处理的音频数据fft卷积即可得到对应的空间音频
2.如果我关于1的描述没有问题的话，假如该wav文件里有512个sample，待处理的音频为双声道，每个音频帧的sample为1024或2048，该如何处理？除此之外，是否需要将左右声道重采样变为单声道？





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月28日(周五) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Asues/Matlab] mit数据库疑问 (Issue #3)




 
这个不好意思，我没有用过这个数据库里的音频文件。我是当年的本科毕业论文用到的学校提供的wav数据，主要有人声，器乐（萨克斯）和白噪音三种音频数据来测试，不过原理应该是大同小异的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by THBratwurst** [comment]
1. wav 是音频文件，不含hrir空间数据，只是音频的采样
2. 第一点不成立。立体声的话你可以把双声道分别处理后再合并即可

**Comment by zuoguangxing11** [comment]
好的，那wav文件的采样要如何与待处理的音频帧对应



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月28日(周五) 晚上6:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Asues/Matlab] mit数据库疑问 (Issue #3)




  
wav 是音频文件，不含hrir空间数据，只是音频的采样 

第一点不成立。立体声的话你可以把双声道分别处理后再合并即可 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by THBratwurst** [comment]
对不起，我不太明白你说的音频帧的概念只得是具体哪方面，如果我理解没问题的话，不知道你是否在询问合成hrtf后会造成合成音频文件长度与原始文件长度不匹配的现象，这个现象我目前还没有仔细研究，主要当时为了测试音频文件，这个并不是主要目的，我毕业都五年多了，相关技术并没有继续深入钻研，实在抱歉～

如有时间的话你可以参考 Brandenburg 教授或者 Werner博士，或者他们下面学生的论文，实在不行可以直接发邮件问他们，这几年来他们一直在研究空间音频。
最后祝新年快乐～
https://www.tu-ilmenau.de/mt-emt

**Comment by zuoguangxing11** [comment]
好的，十分感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月29日(周六) 凌晨1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Asues/Matlab] mit数据库疑问 (Issue #3)




 
对不起，我不太明白你说的音频帧的概念只得是具体哪方面，如果我理解没问题的话，不知道你是否在询问合成hrtf后会造成合成音频文件长度与原始文件长度不匹配的现象，这个现象我目前还没有仔细研究，主要当时为了测试音频文件，这个并不是主要目的，我毕业都五年多了，相关技术并没有继续深入钻研，实在抱歉～
 
如有时间的话你可以参考 Brandenburg 教授或者 Werner博士，或者他们下面学生的论文，实在不行可以直接发邮件问他们，这几年来他们一直在研究空间音频。
 最后祝新年快乐～
 https://www.tu-ilmenau.de/mt-emt
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zuoguangxing11** [comment]
这句话有个疑问：接下来就需要对每一段的音频信号跟相对应空间位置的HRIR函数卷积。这里的算法为 片段1 = 音频段1 * HRIR_0°

请问这里的音频段就是原始的pcm数据吗？是否需要经过频域时域的转换呢？
此外，HRIR_N°里面的采样点数是否要与待卷积的音频段的采样点数对应呢？

**Comment by THBratwurst** [comment]
你自己跑一遍代码就会清楚很多了，在使用前建议稍微学一下Matlab入门，这个跑 Python 也是没问题的，原理大致相同
1. 不需要
2. 可以参考matlab的filter函数说明就明白了
